CREATE TABLE Yolcular (
 YolcuID INT IDENTITY(1,1) PRIMARY KEY ,
 Ad NVARCHAR(50) NOT NULL,
 Soyad NVARCHAR(50) NOT NULL,
 Eposta NVARCHAR(100) UNIQUE NOT NULL,
 Sifre NVARCHAR(255) NOT NULL,
 Telefon NVARCHAR(10),
 Adres NVARCHAR(255),
 Cinsiyet NVARCHAR(10)
);
CREATE TABLE Otobusler (
 OtobusID INT PRIMARY KEY IDENTITY(1,1),
 PlakaNo NVARCHAR(9) UNIQUE NOT NULL,
 Kapasite INT NOT NULL,
 OtobusTuru NVARCHAR(10),
 Model smallint,
 Ozellikler NVARCHAR(100)
);
CREATE TABLE Sehirler (
 SehirID INT PRIMARY KEY IDENTITY(1,1),
 SehirAdi NVARCHAR(15) NOT NULL
 
);
CREATE TABLE Otogarlar (
 OtogarID INT PRIMARY KEY IDENTITY(1,1),
 SehirID INT NOT NULL,
 OtogarAdi NVARCHAR(60) NOT NULL,
 FOREIGN KEY (SehirID) REFERENCES Sehirler(SehirID)
);
CREATE TABLE Seferler (
 SeferID INT PRIMARY KEY IDENTITY(1,1),
 OtobusID INT NOT NULL,
 KalkisOtogarID INT NOT NULL,
 VarisOtogarID INT NOT NULL,
 Kalkis_Tarihi DATETIME NOT NULL,
 Varis_Tarihi DATETIME NOT NULL,
 Fiyat DECIMAL(7, 2) NOT NULL,
 Durum NVARCHAR(20),
 FOREIGN KEY (OtobusID) REFERENCES Otobusler(OtobusID),
 FOREIGN KEY (KalkisOtogarID) REFERENCES Otogarlar(OtogarID),
 FOREIGN KEY (VarisOtogarID) REFERENCES Otogarlar(OtogarID)
);
CREATE TABLE Rezervasyonlar (
 Rez_ID INT PRIMARY KEY IDENTITY(1,1),
 SeferID INT NOT NULL,
 YolcuID INT NOT NULL,
 KoltukNo INT NOT NULL,
 Rez_Tarihi DATETIME NOT NULL,
 YolculukTuru NVARCHAR(20),
 Durum NVARCHAR(20),
 FOREIGN KEY (SeferID) REFERENCES Seferler(SeferID),
 FOREIGN KEY (YolcuID) REFERENCES Yolcular(YolcuID)
);
CREATE TABLE Odemeler (
 OdemeID INT PRIMARY KEY IDENTITY(1,1),
 Rez_ID INT NOT NULL UNIQUE,
 Od_Tarihi DATETIME NOT NULL,
 Od_Yontemi NVARCHAR(20),
 Durum NVARCHAR(20),
 FOREIGN KEY (Rez_ID) REFERENCES Rezervasyonlar(Rez_ID)
);
CREATE TABLE Bildirimler (
 BildirimID INT PRIMARY KEY IDENTITY(1,1),
 YolcuID INT NOT NULL,
 SeferID INT NOT NULL,
 Baslik NVARCHAR(50) NOT NULL,
 MesajIcerigi NVARCHAR(MAX),
 Okundu BIT NOT NULL DEFAULT 0,
 BildirimTuru NVARCHAR(30),
 FOREIGN KEY (YolcuID) REFERENCES Yolcular(YolcuID),
 FOREIGN KEY (SeferID) REFERENCES Seferler(SeferID)
);
CREATE TABLE Sikayetler (
 SikayetID INT PRIMARY KEY IDENTITY(1,1),
 YolcuID INT NOT NULL,
 SeferID INT NOT NULL,
 Konu NVARCHAR(100) NOT NULL,
 Aciklama NVARCHAR(MAX),
 Tarih DATETIME NOT NULL,
 Durum NVARCHAR(20),
 FOREIGN KEY (YolcuID) REFERENCES Yolcular(YolcuID),
 FOREIGN KEY (SeferID) REFERENCES Seferler(SeferID)
);
CREATE TABLE Soforler (
 SoforID INT PRIMARY KEY IDENTITY(1,1),
 Ad NVARCHAR(30) NOT NULL,
 Soyad NVARCHAR(30) NOT NULL,
 Telefon NVARCHAR(10),
 EhliyetNo NVARCHAR(15) UNIQUE NOT NULL,
 CalismaDurumu NVARCHAR(20),
 DeneyimYili smallint
);
CREATE TABLE Operatorler (
 OperatorID INT PRIMARY KEY IDENTITY(1,1),
 OtogarID INT NOT NULL,
 Ad NVARCHAR(30) NOT NULL,
 Soyad NVARCHAR(30) NOT NULL,
 Telefon NVARCHAR(10),
 CalismaDurumu NVARCHAR(20),
 FOREIGN KEY (OtogarID) REFERENCES Otogarlar(OtogarID)
);
CREATE TABLE GecisNoktalari (
 GecisID INT PRIMARY KEY IDENTITY(1,1),
 SeferID INT NOT NULL,
 SehirID INT NOT NULL,
 GecisSirasi INT NOT NULL,
 Kalkis_Saati DATETIME,
 Varis_Saati DATETIME,
 FOREIGN KEY (SeferID) REFERENCES Seferler(SeferID),
 FOREIGN KEY (SehirID) REFERENCES Sehirler(SehirID)
);